#!/bin/bash
curl "https://dle.rae.es/{$1}" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" -s |
	if ! grep -oP '(?<="description": ")(1.*?)(?=")' 
		then echo "term not found"
	fi
